version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.7
            docker: 18
    build:
        commands:
            - docker build -t ips-ci-test /web
    post_build:
        commands:
            - eval `aws ecr get-login --region eu-west-2`
            - docker tag ips-ci-test:latest 014669633018.dkr.ecr.eu-west-2.amazonaws.com/ips-test-repo:latest
            - docker push 014669633018.dkr.ecr.eu-west-2.amazonaws.com/ips-test-repo:latest