version: 0.2

phases:
    install:
        runtime-versions:
            docker: 18
    pre_build:
        commands:
            - eval `aws ecr get-login --no-include-email --region eu-west-2`
            - CURRENT_VERSION=$(aws ecr describe-images --repository-name ips-test-repo --output text --query 'sort_by(imageDetails,& imagePushedAt)[*].imageTags[*]' | tr '\t' '\n' | tail -1)
            - echo $CURRENT_VERSION
            - TEST=0
            - COMMIT_HASH=$(expr $TEST + 1)
            - IMAGE_TAG=${COMMIT_HASH:=latest}
    build:
        commands:
            - docker build -t ips-ci-test ./web/
            
    post_build:
        commands:
            - docker tag ips-ci-test:latest 014669633018.dkr.ecr.eu-west-2.amazonaws.com/ips-test-repo:$IMAGE_TAG
            - docker push 014669633018.dkr.ecr.eu-west-2.amazonaws.com/ips-test-repo:$IMAGE_TAG